name: book_quote_collector_server
description: Starting point for a Serverpod server.

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  serverpod: 2.1.1
  dart_jsonwebtoken: ^2.14.0
  mailer: ^6.1.2
  dotenv: ^4.2.0


dev_dependencies:
  lints: '>=3.0.0 <5.0.0'
